
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.3-apache
        environment:
          - APP_DEBUG: true
          - APP_ENV: testing
          - DB_CONNECTION: mysql
          - DB_DATABASE: attendance
          - DB_USERNAME: root

      - image: circleci/mysql:5.7.29-ram
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: true
          - MYSQL_DATABASE: attendance

    steps:
      - checkout

      - run: sudo apt update
      - run: sudo docker-php-ext-install pdo_mysql

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: echo "APP_KEY=" > .env
      - run: php artisan key:generate
      - run: php artisan migrate

      - run: ./vendor/bin/phpunit

  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - "3a:d2:81:21:1b:70:d7:ea:de:2c:ce:d7:ed:bb:80:48"
      - run: ssh ${USER_NAME}@${HOST_NAME} 'cd /var/www/main_attendance/ && git pull origin master'

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
